name: CI tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

    - name: Install Nextflow 
      run: |
        wget -qO- https://get.nextflow.io | bash
        sudo chmod 755 nextflow
        sudo mv nextflow /usr/local/bin/

    - name: Run tests
      run: |
        for t in `find . -type d -name tests |sort`; do
          pushd $t
          pwd
          ./run_tests.sh
          popd
        done
